
# Excercise: NumPy EDA Excercise

We will generate a small numeric dataset and practice basic NumPy operations seen in class.

In [254]:

# Imports
import numpy as np


## 1) Generate a numeric dataset

We create 500 rows with 6 columns:  
`[day, item, price, qty, discount, paid]`

- Reproducible seed (`np.random.seed`)  
- Discrete sampling (`np.random.choice`, `np.arange`)  
- Continuous values (`np.random.uniform`)  
- Stack columns (`np.column_stack`)

In [255]:
# Reproducible
np.random.seed(42)

In [256]:
# Sizes
N       = 500
n_days  = 30
n_items = 50

In [257]:
# Columns
# TODO : Use Random Choice inside of it np.arange with number of days, size is N     #0..29
day      = np.random.choice(np.arange(0, n_days), N)
day

array([ 6, 19, 28, 14, 10,  7, 28, 20,  6, 25, 18, 22, 10, 10, 23, 20,  3,
        7, 23,  2, 21, 20,  1, 23, 11, 29,  5,  1, 27, 20,  0, 11, 25, 21,
       28, 11, 24, 16, 26, 26,  9, 27, 27, 15, 14, 29, 29, 14, 29, 18, 11,
       22, 19, 24,  2,  4, 18,  6, 20,  8,  6, 17,  3, 24, 27, 13, 17, 25,
        8, 25, 20,  1, 19, 27, 14, 27,  6, 11, 28,  7, 14,  2, 13, 16,  3,
       17,  7,  3,  1, 29,  5, 21,  9,  3, 21, 28, 17, 25, 11,  1,  9, 29,
        3, 13, 15, 14,  7, 13, 22, 27, 24, 29,  7, 20, 15, 12, 17, 14, 20,
       23, 25, 24, 27, 27, 27, 12,  8, 28, 14, 12,  0, 24,  6,  8, 23,  0,
       11,  7, 23, 10, 18, 16,  7,  2,  2,  0, 26,  4,  9,  6, 25,  8, 27,
        6,  8,  7, 11,  1,  0, 15, 22, 22, 29, 23,  4,  2, 11,  7, 21, 26,
        2,  0,  2,  4, 14, 13,  2,  0,  4, 25, 22, 13,  6, 26,  8, 14, 14,
       25,  9, 27, 12, 18,  6, 16, 19, 28,  3, 29,  4, 22,  6, 12, 14, 10,
       28,  3, 12,  6, 26, 18, 21, 27,  1,  9, 12, 29, 24, 20,  5, 27, 27,
       11, 11, 19, 29, 29, 10, 25, 22, 27, 24,  6, 29,  0,  0, 24, 26, 29,
       24, 19, 12,  8,  2,  6,  5,  7, 26,  8, 29,  4,  0, 18,  9, 11, 23,
       14, 26, 21, 23,  8, 19, 16, 29, 16, 25, 19, 11, 29,  6,  1,  2, 16,
        4, 16, 23, 16, 26, 16,  1,  1, 27, 21, 22,  4,  0,  0, 18, 29,  1,
       20, 11, 25,  5, 22,  3, 22, 10, 23, 26, 16,  5, 23,  4, 19,  1,  5,
       21, 10, 15, 15,  0,  8, 27, 26,  5, 15, 28,  2, 19, 27, 26,  3, 18,
       25,  2, 18, 19,  6, 19,  8,  0,  7,  6, 17,  7,  0, 10, 27, 24, 24,
       17, 22, 29,  9,  2,  6, 27, 15, 25, 15, 24, 19, 27, 16,  1,  0, 15,
       29, 11,  4,  4, 26, 22,  8,  8,  2, 18, 15, 15,  2, 19, 23, 21, 23,
        0, 23, 19, 10, 16,  7,  3,  5,  7, 19, 29,  2, 15, 29, 24,  2, 24,
       28, 17, 13, 17,  1, 21,  2, 15, 28,  8,  3,  0,  3,  0, 13, 20, 15,
       19, 23,  7,  6,  2, 16,  0, 15, 11, 26, 18, 21, 22, 21, 13, 29,  5,
        5, 12, 18, 21,  7, 26, 26,  1, 20, 29,  0, 27, 14,  0,  4, 27, 28,
       15, 18,  3,  2, 16, 16, 11, 27, 29, 28, 13, 20,  5,  2, 27,  8,  4,
       23, 28, 16, 13, 20,  2, 27,  0, 19, 28, 20, 22,  0,  2, 17, 24,  9,
       21, 25,  2,  7, 13, 23, 17, 14, 21, 22,  1, 26,  9,  1, 25, 16,  7,
        0,  8, 10, 21, 15,  6, 28])

In [258]:

# TODO : Use Random Choice inside of it np.arange with number of items, size is N        # 0..49
item     =    np.random.choice(np.arange(0, n_items), N)
item

array([41, 25, 34, 49, 24, 23, 12,  6, 35, 44, 19,  0,  7, 45, 15, 13, 11,
       22, 14, 27, 33,  1, 31, 22, 21, 24, 21, 21, 48, 41,  5, 14, 42, 36,
       32,  7, 43, 43,  4, 38,  3,  5, 44, 31, 29, 46, 34, 39, 15, 12, 49,
       41, 29, 18, 16, 18, 27, 25, 36, 25, 22,  8, 11,  0,  0, 46, 33, 31,
       47, 24, 39, 44,  0, 15, 38,  4, 21, 28,  2, 11, 25, 15, 36, 21, 28,
       13, 27,  4, 46, 48, 29, 45,  4, 11, 15, 25, 25, 47, 20, 38, 35, 32,
       29, 36, 22,  9,  4, 35, 33, 30,  9, 18, 31,  0,  4, 44,  3, 15, 23,
       15,  1, 48, 27, 31, 26, 19, 23, 11, 49, 34, 32, 32, 42, 36, 11,  2,
        0, 32, 39,  9, 42, 43, 28, 12, 11, 30, 45,  1, 49, 34, 22, 16, 25,
        7, 28, 25,  9, 25, 33, 40,  6,  3, 49, 44, 10, 28, 35, 24, 20, 35,
        9, 36,  8, 23, 34, 48, 34, 47, 35, 17, 48, 38, 31, 23, 22, 31, 36,
       11, 48, 12, 22, 24, 34, 40, 29, 16, 48, 19, 47, 24, 21, 12, 18, 48,
       35, 11, 40, 18, 11,  8,  6, 27, 13, 30, 18, 46, 15,  4, 34, 11, 24,
       20, 35, 22, 15, 38, 44, 41, 38, 13, 30,  4, 34, 22, 28, 42, 10, 17,
       46, 11,  8,  9, 43, 16, 37,  6, 45, 12, 39, 41,  8, 49, 26,  1,  4,
       28, 36, 37, 18,  7, 47, 44,  0, 21, 16,  6, 24, 44,  3, 35,  5, 30,
       18, 43, 38, 26,  9, 25, 18, 38,  2, 44, 12, 49, 27, 19, 27,  7, 40,
       38,  0,  2, 12, 27, 48, 24, 32, 37,  5, 43, 44, 31, 44, 46, 20, 15,
       20, 10, 36, 35, 34, 18, 19, 17, 46, 40, 48, 13, 14, 30,  0,  2, 15,
       22, 10, 11,  9, 31, 15,  7, 37, 11, 23, 27,  7, 27, 35, 25,  7, 49,
       27, 27, 36, 40, 35, 26, 16,  8, 32, 19, 12, 27, 47, 28, 12, 45, 34,
        5, 17,  4, 46, 24,  1,  9, 29, 49, 44,  4, 32,  0, 17, 31, 46, 48,
       10, 20, 25, 24, 21, 26, 48, 12, 32, 33, 40, 34,  0, 20, 47,  5, 27,
       16,  4, 30,  4, 37,  2, 22, 36, 36,  9,  9, 18, 16, 20, 13,  8, 45,
        0, 44, 12,  3,  0, 48, 39, 31, 33, 27, 30,  7, 38, 25, 33,  2, 49,
       11,  0, 43,  4, 29, 29, 16, 47, 46, 22, 14, 36, 20, 13,  1, 10, 38,
       37, 33, 37, 49, 33, 17, 29, 14, 26, 33, 37, 32, 23, 14, 29, 41, 16,
        4, 28,  3,  9, 16,  9, 16, 19, 23,  4, 33,  5,  1, 12, 42, 42, 47,
       10, 46, 22, 15, 30, 10, 15,  7,  3, 39,  3, 24,  2, 31,  2, 26, 28,
       31, 49, 18, 20,  4, 17, 27])

In [259]:

# TODO : Use Random uniform from 5 to 50 with size N                # price (float)
price    = np.random.uniform(5, 50, N)
price

array([20.64286465,  6.43121067, 29.69218891, 29.04905767, 21.01961679,
       45.23977683, 10.79367792, 19.8544781 , 19.47122441,  9.15307638,
       26.65154273, 35.95031227, 28.02456561, 12.06399572, 21.97786844,
        5.1167761 , 44.07354982,  8.80326535, 31.8775137 , 49.38156481,
       29.14657907, 46.58187916, 15.62524399, 39.1979934 , 28.90695893,
       37.42322276,  7.80536131, 11.64825914, 10.99026179, 35.92244774,
       42.99983027, 38.73273044,  6.37124687, 44.02467415, 20.93660019,
       22.87237246,  9.71911249, 38.18323427, 13.20277453, 30.37842914,
       42.83194936,  9.01419479, 29.09010038, 15.49473852, 20.43170889,
       26.32864736, 20.97969365, 34.19702781, 26.58119458, 31.28897681,
       38.15701139, 30.09840197, 31.39409456, 30.40063441, 22.04476817,
       20.18510752, 45.48413287, 32.339985  , 15.995892  , 27.4211464 ,
       19.86568166, 47.01613207,  5.33904634, 15.1399759 , 21.44105689,
       26.95144104, 43.2867883 ,  8.9549431 , 41.2639199 ,  7.50440702,
       42.90413159,  7.3235965 ,  5.82091166, 36.36326581, 49.87649906,
       45.34746183, 30.9199288 , 46.28280259,  5.23850029, 48.87802233,
       27.08369507, 37.53032435, 41.93876629, 37.33057719, 29.07665294,
       26.44787679, 42.73621514, 14.22849021, 48.55973299, 36.99286155,
       13.97781173, 38.13112327, 28.84280104, 36.8253543 , 39.55007756,
        8.92805808, 27.77467804, 46.9406454 , 19.42889865, 31.72473939,
       21.61537167, 25.44205875, 29.68714031, 29.7014891 , 14.0778708 ,
       35.80571965,  8.95406501, 11.2471148 ,  5.12199047, 10.25132289,
       26.29247905, 32.27458465, 40.74302525,  9.80146626, 43.2827357 ,
       38.56885365, 23.38332318, 46.98221302, 49.59182644, 14.22508145,
       22.06528632, 46.69022406, 37.47184478,  7.16425898, 40.16815168,
       42.25733992, 38.77258661, 40.97917089, 42.13097045, 13.38822441,
       15.60612857, 33.51913537, 45.85397587, 19.2288462 , 31.47380041,
       35.73419285, 25.33768706, 37.12021047, 45.48503504, 33.08456949,
       29.29014779, 24.74351039, 30.98688219, 20.99131033, 22.61669496,
       28.93358659,  7.99786006, 15.30614259, 29.42821898, 24.41876644,
       19.97671037, 37.87471116, 36.21729233, 12.5028842 , 44.53831019,
       27.29406319, 38.365741  , 30.79178822, 49.89616772, 38.8581404 ,
       36.81412076, 40.03573726, 11.44075935, 14.20450669, 37.1328837 ,
       27.22916692, 38.95858813,  9.63122138, 29.14166082, 22.04697045,
       25.56500987, 32.17810424, 27.60297564, 29.29372867, 26.88608669,
       23.40298297, 39.73468913,  5.54913825, 31.92992155, 30.44787563,
       37.22805836, 31.95632141, 42.20594725, 48.15836576, 20.41359157,
       15.23079424, 24.06185881, 17.95683274, 32.67276184, 46.0333584 ,
       11.26022874,  9.53575714, 16.52069893, 37.67430137, 31.68333074,
        9.59956989, 46.3437735 , 40.55380867,  6.03601722, 34.31152449,
       39.70610008, 21.84959164,  8.10146927,  8.47944795,  9.69111347,
       42.81978344, 45.98087892, 10.52648518, 15.61577156, 12.44842297,
       13.38443958, 42.68708551, 19.94658857, 19.01499188, 15.23280294,
       32.35524772, 22.06875643, 38.49123433, 14.25109138, 40.45054499,
       32.16746893, 10.1420285 , 23.65270629, 43.85831633, 46.53321043,
       25.9565055 , 26.63766401, 46.33046262, 31.41807009,  6.47810016,
       46.07372583, 16.17018992, 30.99343793, 12.44809928,  6.52456221,
       19.0162927 , 40.12230684, 17.49142277, 14.90437463, 14.5706353 ,
       28.18281571, 48.89935921, 25.65450446, 30.0787416 , 43.72844081,
       29.07813735, 13.30082921, 18.48181603, 18.94716168, 22.8793152 ,
       24.20550074, 40.99019099, 20.72241496, 26.07043228, 33.12391942,
       21.99766763, 42.6454166 , 31.43541219, 18.23201056, 37.13266399,
       28.74414786, 29.05051511, 26.64895768, 27.3655377 , 39.44103265,
        9.63416657, 20.04632651,  8.39765137, 38.89607993, 17.25358346,
       45.38436844, 28.696031  , 41.03373972, 49.0519146 , 42.79049868,
       44.0147192 , 23.35930229, 29.82751679, 16.42498538, 13.82508949,
       27.74785456, 31.77720409, 20.26720607, 30.6249583 , 44.93572171,
       30.05247132, 37.43658933, 41.23917353, 49.49279519, 32.1438831 ,
       41.3082567 , 48.31921933, 47.49843765, 11.34868319, 23.28765387,
       19.57955275,  8.91162567, 33.49583487, 38.11570759, 43.1657643 ,
       10.52496003, 44.43998341, 33.93165036, 36.67757608, 45.97808016,
       33.1142572 , 20.11396357, 42.12982991, 21.33766455,  6.54026499,
       42.3794528 , 20.53364652, 39.82255354, 21.32410526, 43.7480609 ,
       14.87797363, 48.85462693, 40.08914487, 10.14070667, 30.4599479 ,
       49.34152905, 26.19794537, 13.19482125, 26.81502652, 28.06059451,
       38.37591249, 36.44806339, 23.11475196, 14.81103984, 34.02743755,
       23.97667705, 10.9524295 , 45.52575356, 36.10498359, 35.74327354,
       42.01627442, 28.83477554, 41.67744928, 27.41408391,  8.022893  ,
       23.23616396, 27.38592023, 37.40911617,  9.79604286, 11.30083424,
       16.86577112, 16.9924277 , 37.94830603, 16.28287973, 33.48941285,
       27.24232326, 30.79824702, 42.71481334, 23.19716757, 39.69101197,
       23.99162268, 20.92421195, 48.13822298, 13.29669143,  9.06516323,
       39.69436665,  8.07123674, 42.66855458, 24.67370284, 46.19811548,
       37.46897875, 32.46821002, 47.71880587, 22.84922179, 47.93391214,
       11.07505748, 26.76897239, 17.14600501, 29.29292505, 12.29062451,
       42.86883471, 43.08835322, 47.98563407, 11.96024634, 33.04996479,
       26.34067889, 20.49726794, 20.81930725, 23.57570978, 36.72164974,
       31.92287262, 25.68566807,  8.41700347,  8.49944048,  5.10527258,
       48.54647247,  5.23642184,  9.63921857, 19.15684506, 41.33436133,
       48.29444536, 40.55061015, 36.07521046, 28.45853003,  8.90173453,
       48.11768569, 39.12765863, 33.75272234, 39.15661305, 37.58464982,
       33.67542109, 49.12595601, 45.65137157, 34.09992136, 36.19288452,
        7.3218113 , 35.1462859 ,  6.9874447 , 31.47186906, 49.97090748,
       30.01129616, 26.29445531, 19.07846854, 10.42351605, 37.89606522,
       13.66695625, 10.18769096, 23.97931969, 40.79038271, 38.52790467,
        7.46971766, 25.48146583, 28.50955592, 34.00459928, 34.25753077,
       21.41137623, 30.23047373, 26.64778477, 44.82492604, 28.86193097,
       24.84644728, 23.20184524, 30.75924917, 41.17896407, 29.22806707,
       34.77448288, 38.20350951, 28.40756494, 24.20676755, 44.449942  ,
       23.78777378, 25.78742828, 49.5653591 ,  5.01068856, 13.34628093,
       22.27837505, 46.96654592,  8.15133676,  5.42684451,  7.37077262,
        8.98445348,  6.69185479, 26.59015971, 31.13407433, 17.2259137 ,
       22.92293228,  9.12647008, 20.13667087, 28.51336362, 37.95223132,
        5.15058629, 26.02898449, 18.36512944, 43.37698198, 37.19989919,
       31.50988405, 17.47695406, 45.96525959,  7.02953047,  9.92604194,
       22.62335632, 10.59969008, 48.03870639, 40.9095195 , 16.65421932,
       31.4849403 , 49.20487318, 44.78895402, 32.03593009, 45.66757852,
       49.51332094, 38.45087703,  7.92438843, 23.07111064, 42.70215809,
       15.37561381, 42.3789133 , 10.41524429,  7.11254107, 22.28407752,
        6.65293718, 48.07716183, 42.17925631, 41.03463592, 33.34000653])

In [260]:

# TODO : Use Random Choice inside of it numpy array [1,2,3,4,5], size is N        # quantity (int-like)
qty      =  np.random.choice(np.array([1,2,3,4,5]), N)
qty

array([1, 1, 3, 4, 2, 1, 5, 3, 2, 3, 2, 2, 1, 3, 3, 5, 5, 1, 1, 4, 5, 2,
       3, 1, 3, 3, 4, 5, 1, 3, 1, 2, 4, 2, 1, 1, 5, 3, 3, 2, 4, 3, 5, 2,
       2, 5, 4, 5, 4, 5, 5, 1, 2, 5, 5, 3, 2, 3, 2, 3, 5, 5, 1, 3, 4, 1,
       3, 3, 1, 5, 3, 5, 1, 5, 2, 4, 3, 4, 5, 3, 5, 2, 1, 3, 2, 2, 3, 5,
       2, 4, 2, 5, 5, 4, 2, 5, 3, 1, 1, 1, 2, 4, 5, 3, 3, 2, 1, 2, 4, 4,
       5, 5, 4, 4, 4, 2, 4, 3, 1, 4, 1, 2, 1, 2, 3, 2, 2, 5, 4, 4, 3, 3,
       4, 5, 4, 5, 3, 1, 3, 3, 2, 2, 2, 2, 5, 4, 1, 3, 5, 1, 5, 5, 3, 4,
       2, 4, 3, 3, 3, 1, 4, 4, 5, 5, 5, 3, 4, 3, 1, 5, 3, 3, 1, 2, 4, 2,
       5, 3, 1, 1, 4, 2, 4, 3, 4, 1, 1, 5, 5, 3, 2, 4, 3, 5, 4, 5, 4, 2,
       3, 4, 1, 1, 4, 4, 4, 1, 1, 4, 5, 5, 2, 3, 5, 1, 5, 2, 2, 3, 5, 1,
       1, 4, 1, 3, 3, 1, 1, 4, 1, 4, 4, 1, 2, 2, 4, 1, 2, 1, 1, 1, 5, 1,
       5, 4, 2, 2, 2, 2, 2, 2, 2, 4, 1, 3, 5, 3, 3, 1, 1, 1, 2, 4, 2, 4,
       4, 3, 3, 4, 4, 2, 2, 3, 1, 4, 2, 3, 2, 4, 4, 5, 1, 5, 3, 2, 3, 4,
       5, 5, 5, 3, 4, 2, 2, 3, 5, 1, 3, 3, 4, 2, 3, 3, 5, 5, 1, 4, 1, 5,
       2, 5, 4, 5, 4, 4, 4, 4, 4, 2, 1, 3, 1, 4, 2, 5, 2, 4, 2, 2, 4, 2,
       3, 3, 2, 5, 4, 3, 5, 2, 5, 1, 3, 2, 4, 2, 4, 2, 5, 5, 5, 1, 4, 5,
       1, 4, 2, 1, 3, 1, 1, 4, 2, 3, 5, 5, 1, 4, 4, 5, 3, 2, 3, 2, 5, 2,
       4, 1, 1, 5, 4, 3, 4, 1, 1, 4, 4, 1, 3, 5, 5, 4, 5, 1, 1, 4, 4, 4,
       3, 5, 4, 2, 2, 1, 5, 4, 2, 5, 1, 3, 5, 5, 3, 5, 1, 1, 3, 4, 2, 4,
       5, 2, 3, 3, 2, 1, 2, 5, 1, 3, 2, 4, 4, 5, 4, 2, 2, 4, 2, 5, 1, 5,
       5, 2, 1, 2, 3, 2, 2, 2, 1, 2, 1, 4, 3, 1, 4, 1, 1, 3, 5, 5, 1, 2,
       4, 2, 2, 1, 1, 1, 1, 5, 1, 5, 5, 1, 3, 4, 2, 5, 4, 3, 2, 2, 5, 1,
       3, 5, 3, 1, 1, 5, 1, 4, 2, 5, 3, 4, 5, 1, 1, 1])

In [261]:

# TODO : Use Random uniform from 0 to 5 with size N                        # discount (float)
discount = np.random.uniform(0, 5, N)
discount

array([2.72843444e+00, 2.22209726e+00, 7.33352852e-02, 2.93530854e+00,
       8.42221926e-01, 3.21287984e+00, 3.79672164e+00, 2.50222655e+00,
       2.71181832e+00, 4.75739280e+00, 4.23583681e+00, 4.57118258e+00,
       4.06883144e+00, 5.44591709e-01, 7.44959280e-01, 2.63311899e+00,
       1.23034829e+00, 2.38347738e+00, 1.97182662e+00, 2.74707119e+00,
       3.73437858e+00, 3.57745454e+00, 2.60617066e+00, 4.11196709e+00,
       2.15431046e+00, 4.48357145e+00, 3.56401350e-01, 4.77330015e+00,
       3.27346541e+00, 1.90037254e+00, 9.85770633e-01, 2.39591615e+00,
       9.72791616e-01, 8.31658039e-01, 3.08675879e+00, 2.61542362e+00,
       3.35048017e+00, 4.64802939e+00, 2.66130107e+00, 2.90466027e+00,
       4.48131696e-01, 3.58817893e+00, 1.99952603e+00, 4.88362619e+00,
       4.11587008e+00, 2.61240520e+00, 6.16113271e-01, 4.29707897e+00,
       3.99890548e+00, 9.22925648e-01, 1.47639145e+00, 3.96703629e+00,
       9.26142233e-01, 4.58876245e+00, 2.12263713e+00, 4.35194813e-01,
       4.07874322e+00, 1.86754842e+00, 2.63249597e+00, 5.61521722e-01,
       1.29200742e-02, 3.18992603e+00, 2.57587585e+00, 2.96769285e+00,
       3.96871925e+00, 3.23302957e+00, 8.73867214e-01, 1.80386260e+00,
       4.52945552e+00, 3.84972350e+00, 2.78318529e+00, 1.27822499e+00,
       1.51030251e+00, 3.65979034e+00, 4.25587130e+00, 3.35712335e+00,
       4.04764988e+00, 3.83328068e+00, 7.48519840e-01, 2.11972406e+00,
       7.64919004e-01, 1.17617792e+00, 4.34629812e+00, 2.36445983e+00,
       2.67679051e+00, 8.92229826e-01, 1.56135893e+00, 1.15123084e+00,
       1.03093082e+00, 3.18980397e+00, 1.28441924e+00, 3.16007743e+00,
       2.92273071e-01, 7.08871968e-01, 1.37270127e+00, 2.98523458e+00,
       3.37920623e+00, 2.21358483e+00, 2.22895457e+00, 3.62258426e+00,
       7.91054588e-02, 1.70545012e+00, 4.09353529e+00, 3.01609705e+00,
       1.68613566e+00, 4.52762396e+00, 3.86311364e+00, 1.32447724e+00,
       3.22644919e+00, 2.97875364e+00, 2.00593957e+00, 1.83478040e+00,
       1.71780237e+00, 3.08577892e+00, 2.21204968e+00, 4.15931557e+00,
       3.34801308e+00, 3.49658029e-01, 3.20084112e+00, 1.35573718e+00,
       2.96405996e+00, 3.40065966e+00, 1.15414595e+00, 2.28429322e+00,
       9.51624314e-01, 2.61694379e-01, 1.89238212e+00, 1.81472136e+00,
       4.97740245e+00, 2.23176176e+00, 1.66784775e+00, 2.90237503e+00,
       4.43836971e-01, 4.80832868e+00, 3.17480023e+00, 3.77418910e+00,
       8.52389691e-01, 2.04738927e+00, 2.11344557e+00, 4.10903222e+00,
       6.18339880e-03, 1.50426554e+00, 4.90618187e+00, 2.37443272e+00,
       1.91263140e+00, 5.99145010e-01, 4.87082314e+00, 1.00131780e-01,
       3.68590113e+00, 3.84299902e+00, 1.21828358e+00, 3.35779222e+00,
       4.64645722e-01, 1.28523633e+00, 3.93950994e+00, 4.32343096e+00,
       3.04243206e+00, 2.53419216e+00, 7.96520103e-01, 3.15545165e-01,
       5.88245142e-01, 1.13678650e+00, 1.70837251e+00, 1.90454763e+00,
       1.73160884e+00, 1.19527666e+00, 2.54862123e+00, 4.12643054e+00,
       1.39851769e+00, 4.71193510e+00, 4.36668331e+00, 8.08821057e-01,
       3.93137978e+00, 2.87293691e+00, 2.83287681e+00, 1.95521382e+00,
       2.50576500e+00, 1.98589389e+00, 2.69866309e+00, 3.13975026e+00,
       3.37151903e+00, 2.66240596e+00, 3.60711034e+00, 7.06390246e-01,
       1.05991245e+00, 4.09367502e+00, 1.61263989e+00, 1.14469125e-01,
       7.68955748e-01, 1.11807217e+00, 4.78661444e+00, 2.86520714e+00,
       4.66365370e+00, 2.87581675e+00, 2.39677220e+00, 1.56863846e+00,
       3.03185472e+00, 6.95990123e-01, 4.49130814e+00, 4.14666203e+00,
       1.58765724e+00, 4.76398764e+00, 4.12600384e+00, 3.33153443e+00,
       6.08809556e-01, 2.39117012e+00, 2.53053777e+00, 1.16275679e+00,
       3.99826972e-01, 3.88361815e+00, 6.10175261e-01, 2.97145375e+00,
       4.68224587e+00, 4.38052596e+00, 1.38876312e+00, 4.25724319e+00,
       1.66253060e-03, 8.84390481e-02, 3.01276582e+00, 1.82399110e+00,
       1.93230421e+00, 2.82220545e+00, 9.58912278e-01, 1.05877675e+00,
       2.42300794e+00, 3.77126772e+00, 3.09748876e+00, 1.48677524e+00,
       2.15168589e+00, 8.53323793e-01, 3.73149072e-01, 3.91348020e+00,
       1.32693705e+00, 8.88831939e-01, 3.45809028e+00, 3.09025837e+00,
       3.16594813e+00, 1.14447302e+00, 1.16322769e+00, 1.10401315e+00,
       8.68762978e-01, 3.27861836e+00, 4.24007943e+00, 3.62158735e+00,
       3.96046817e+00, 2.02399215e+00, 3.27037898e+00, 1.77118120e+00,
       2.62752311e+00, 2.40817423e+00, 8.84435726e-01, 1.93539380e+00,
       4.81911138e+00, 1.24290129e+00, 6.69018681e-01, 2.09290311e+00,
       3.95168868e+00, 2.91074115e+00, 3.40487414e+00, 9.48474241e-01,
       3.09474097e+00, 1.61750197e+00, 4.17151683e+00, 3.14649403e+00,
       9.94281389e-01, 3.23083399e-01, 2.13166046e-01, 1.85704284e+00,
       1.32925568e+00, 3.23045062e+00, 2.49666917e+00, 1.33009639e+00,
       7.46188890e-01, 6.35998813e-01, 4.32330196e+00, 1.21738984e+00,
       3.25855324e+00, 4.05342964e+00, 3.07040656e+00, 4.29782616e+00,
       1.96196861e+00, 4.78111095e+00, 6.65725021e-01, 5.10747648e-01,
       3.29346073e+00, 4.71415571e+00, 4.04441731e+00, 3.82084297e-01,
       1.39683857e+00, 4.65159442e+00, 1.26529216e+00, 3.90585212e+00,
       4.12566098e+00, 2.47726052e+00, 1.93174455e+00, 2.25062216e+00,
       1.13482347e+00, 4.44695458e+00, 2.25309828e+00, 4.41229720e+00,
       5.28467400e-01, 4.94137636e+00, 2.21636544e+00, 2.39154102e-01,
       1.90109241e-01, 3.73103629e+00, 3.29517767e+00, 4.01065279e+00,
       5.26837670e-01, 1.77854335e-01, 2.54289645e+00, 1.93797616e+00,
       2.30973468e+00, 4.95794204e+00, 4.85374979e+00, 4.71157695e+00,
       3.91921338e+00, 1.77420680e+00, 2.06065465e+00, 2.74808022e+00,
       4.15267228e+00, 3.43564163e-01, 2.12148443e+00, 4.13088317e-01,
       2.57328793e+00, 4.49450412e+00, 3.91242462e+00, 1.13921209e+00,
       4.87995425e+00, 3.33675199e+00, 5.21384970e-02, 1.27706742e+00,
       1.30356650e+00, 3.46271531e-01, 4.79913259e+00, 2.39127647e+00,
       4.47907299e+00, 1.61107752e+00, 6.26167852e-01, 2.37168055e+00,
       5.69783174e-01, 2.43007751e+00, 4.60148591e+00, 2.60384071e+00,
       3.08249863e+00, 7.83192185e-01, 2.18678129e-01, 5.54039811e-01,
       2.99265788e+00, 4.75058495e-01, 1.87996445e+00, 2.75045970e+00,
       1.94326399e+00, 8.18419007e-01, 1.36895654e+00, 4.64158766e+00,
       3.37991138e+00, 2.48023919e+00, 6.35744499e-02, 4.96207700e+00,
       3.35727467e+00, 1.58461239e+00, 4.39634330e+00, 1.29215810e+00,
       2.72008290e+00, 3.18035382e+00, 1.10531686e+00, 4.89198639e+00,
       3.74095953e+00, 2.78906613e+00, 9.02972991e-01, 2.69291035e-01,
       1.60029916e+00, 3.76593668e+00, 1.34665649e+00, 2.69778110e+00,
       3.63973588e+00, 5.39718573e-01, 3.42649008e+00, 4.59354439e-01,
       4.82564871e+00, 2.44197065e+00, 7.53380539e-01, 1.71191818e+00,
       2.06708225e+00, 3.79092506e+00, 3.71711893e+00, 3.05970253e+00,
       5.29653563e-01, 7.57846858e-01, 4.68784603e-01, 2.88586392e+00,
       4.38569221e+00, 2.16900256e+00, 8.04240870e-01, 2.79021163e+00,
       4.05876108e+00, 3.70856031e+00, 4.40725390e+00, 1.38951049e+00,
       9.69769336e-01, 4.39908243e+00, 3.28780156e+00, 1.55464465e+00,
       3.71174025e+00, 4.07559192e+00, 3.07489120e+00, 3.43942055e+00,
       1.87629952e+00, 2.69347834e+00, 2.62079585e+00, 4.24023896e+00,
       4.19981990e+00, 4.16340235e+00, 5.51580713e-02, 3.74772742e+00,
       3.79338195e+00, 3.39189411e+00, 3.78132329e+00, 4.20985186e+00,
       2.35159527e+00, 2.51025107e+00, 6.23570285e-01, 1.92687942e+00,
       3.21682590e+00, 3.90199888e+00, 1.08604549e+00, 6.89114496e-01,
       3.31521002e+00, 9.39941762e-03, 8.91862922e-01, 1.45356902e-01,
       8.34425589e-01, 9.06596400e-01, 1.93836797e+00, 2.01163562e+00,
       4.37131235e+00, 2.55054856e+00, 3.61702383e+00, 5.20686790e-01,
       1.12719378e+00, 3.51471720e+00, 2.64019802e-01, 2.43298831e+00,
       2.99684483e+00, 3.01072822e+00, 1.14664056e-01, 1.61054002e+00,
       3.18245326e+00, 7.44998681e-01, 3.47707824e+00, 3.72962604e+00,
       4.90984595e+00, 1.04920997e+00, 4.12565334e+00, 2.60148288e+00,
       1.86731298e+00, 6.11883787e-01, 3.67752803e+00, 1.17928800e+00,
       1.85711001e+00, 3.12711134e-01, 4.00683458e+00, 3.83294262e+00,
       3.66807915e+00, 1.49721755e+00, 8.67400371e-01, 3.18776632e+00,
       2.48083192e+00, 8.91262335e-01, 3.42955636e+00, 4.95563216e+00,
       3.73609794e+00, 3.69993193e+00, 4.75156376e+00, 1.01468184e+00,
       2.82774982e+00, 4.89823358e+00, 8.26470555e-01, 3.50125980e+00,
       2.92905073e+00, 2.93239546e+00, 3.48835314e+00, 4.64808461e+00,
       3.91290970e+00, 2.80680517e-01, 4.26364010e+00, 1.12770665e+00,
       1.88457082e+00, 2.30866407e+00, 2.40453000e+00, 2.17590200e+00,
       4.68676647e+00, 3.53009504e+00, 3.15585323e+00, 2.49210139e-01,
       4.51956665e+00, 4.54695096e+00, 3.90106532e+00, 3.51460191e-02])

In [262]:

# TODO : Use Random Choice inside of it numpy array [0,1], size is N           # 0=cancel, 1=paid
paid     = np.random.choice(np.array([0,1]), N)
paid

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0])

In [263]:

# TODO : Assemble design matrix (note: dtype will be float due to float columns) , hint use column stack
X = np.column_stack((day, item, price, qty, discount, paid))
X

array([[6.00000000e+00, 4.10000000e+01, 2.06428647e+01, 1.00000000e+00,
        2.72843444e+00, 0.00000000e+00],
       [1.90000000e+01, 2.50000000e+01, 6.43121067e+00, 1.00000000e+00,
        2.22209726e+00, 1.00000000e+00],
       [2.80000000e+01, 3.40000000e+01, 2.96921889e+01, 3.00000000e+00,
        7.33352852e-02, 1.00000000e+00],
       ...,
       [1.50000000e+01, 4.00000000e+00, 4.21792563e+01, 1.00000000e+00,
        4.54695096e+00, 0.00000000e+00],
       [6.00000000e+00, 1.70000000e+01, 4.10346359e+01, 1.00000000e+00,
        3.90106532e+00, 1.00000000e+00],
       [2.80000000e+01, 2.70000000e+01, 3.33400065e+01, 1.00000000e+00,
        3.51460191e-02, 0.00000000e+00]])

In [264]:
print("Shape (rows, cols):", X.shape)
print("First 5 rows:")
print(np.round(X[:5], 2))
print("\nColumn order = [day, item, price, qty, discount, paid]")

Shape (rows, cols): (500, 6)
First 5 rows:
[[ 6.   41.   20.64  1.    2.73  0.  ]
 [19.   25.    6.43  1.    2.22  1.  ]
 [28.   34.   29.69  3.    0.07  1.  ]
 [14.   49.   29.05  4.    2.94  1.  ]
 [10.   24.   21.02  2.    0.84  1.  ]]

Column order = [day, item, price, qty, discount, paid]


## 2) Introduce missing values (NaNs) in **`price`** column

Pick **`price`** column and set a few entries to `NaN` to simulate messy data.

In [265]:

# TODO : Choose 15 random row indices , use random.choice, inside of it arange(N) and size = 15)
nan_idx =  np.random.choice(np.arange(N), 15)
nan_idx

array([431, 157, 267,  34, 266,  63, 493,  49, 468, 254, 148, 324, 303,
       275, 356])

In [266]:

## ? Google isnan method
# TODO : Add NaNs to chosen column <- `a[np.isnan(a)]`
price[nan_idx] = np.nan
price

array([20.64286465,  6.43121067, 29.69218891, 29.04905767, 21.01961679,
       45.23977683, 10.79367792, 19.8544781 , 19.47122441,  9.15307638,
       26.65154273, 35.95031227, 28.02456561, 12.06399572, 21.97786844,
        5.1167761 , 44.07354982,  8.80326535, 31.8775137 , 49.38156481,
       29.14657907, 46.58187916, 15.62524399, 39.1979934 , 28.90695893,
       37.42322276,  7.80536131, 11.64825914, 10.99026179, 35.92244774,
       42.99983027, 38.73273044,  6.37124687, 44.02467415,         nan,
       22.87237246,  9.71911249, 38.18323427, 13.20277453, 30.37842914,
       42.83194936,  9.01419479, 29.09010038, 15.49473852, 20.43170889,
       26.32864736, 20.97969365, 34.19702781, 26.58119458,         nan,
       38.15701139, 30.09840197, 31.39409456, 30.40063441, 22.04476817,
       20.18510752, 45.48413287, 32.339985  , 15.995892  , 27.4211464 ,
       19.86568166, 47.01613207,  5.33904634,         nan, 21.44105689,
       26.95144104, 43.2867883 ,  8.9549431 , 41.2639199 ,  7.50440702,
       42.90413159,  7.3235965 ,  5.82091166, 36.36326581, 49.87649906,
       45.34746183, 30.9199288 , 46.28280259,  5.23850029, 48.87802233,
       27.08369507, 37.53032435, 41.93876629, 37.33057719, 29.07665294,
       26.44787679, 42.73621514, 14.22849021, 48.55973299, 36.99286155,
       13.97781173, 38.13112327, 28.84280104, 36.8253543 , 39.55007756,
        8.92805808, 27.77467804, 46.9406454 , 19.42889865, 31.72473939,
       21.61537167, 25.44205875, 29.68714031, 29.7014891 , 14.0778708 ,
       35.80571965,  8.95406501, 11.2471148 ,  5.12199047, 10.25132289,
       26.29247905, 32.27458465, 40.74302525,  9.80146626, 43.2827357 ,
       38.56885365, 23.38332318, 46.98221302, 49.59182644, 14.22508145,
       22.06528632, 46.69022406, 37.47184478,  7.16425898, 40.16815168,
       42.25733992, 38.77258661, 40.97917089, 42.13097045, 13.38822441,
       15.60612857, 33.51913537, 45.85397587, 19.2288462 , 31.47380041,
       35.73419285, 25.33768706, 37.12021047, 45.48503504, 33.08456949,
       29.29014779, 24.74351039, 30.98688219, 20.99131033, 22.61669496,
       28.93358659,  7.99786006, 15.30614259,         nan, 24.41876644,
       19.97671037, 37.87471116, 36.21729233, 12.5028842 , 44.53831019,
       27.29406319, 38.365741  ,         nan, 49.89616772, 38.8581404 ,
       36.81412076, 40.03573726, 11.44075935, 14.20450669, 37.1328837 ,
       27.22916692, 38.95858813,  9.63122138, 29.14166082, 22.04697045,
       25.56500987, 32.17810424, 27.60297564, 29.29372867, 26.88608669,
       23.40298297, 39.73468913,  5.54913825, 31.92992155, 30.44787563,
       37.22805836, 31.95632141, 42.20594725, 48.15836576, 20.41359157,
       15.23079424, 24.06185881, 17.95683274, 32.67276184, 46.0333584 ,
       11.26022874,  9.53575714, 16.52069893, 37.67430137, 31.68333074,
        9.59956989, 46.3437735 , 40.55380867,  6.03601722, 34.31152449,
       39.70610008, 21.84959164,  8.10146927,  8.47944795,  9.69111347,
       42.81978344, 45.98087892, 10.52648518, 15.61577156, 12.44842297,
       13.38443958, 42.68708551, 19.94658857, 19.01499188, 15.23280294,
       32.35524772, 22.06875643, 38.49123433, 14.25109138, 40.45054499,
       32.16746893, 10.1420285 , 23.65270629, 43.85831633, 46.53321043,
       25.9565055 , 26.63766401, 46.33046262, 31.41807009,  6.47810016,
       46.07372583, 16.17018992, 30.99343793, 12.44809928,  6.52456221,
       19.0162927 , 40.12230684, 17.49142277, 14.90437463, 14.5706353 ,
       28.18281571, 48.89935921, 25.65450446, 30.0787416 , 43.72844081,
       29.07813735, 13.30082921, 18.48181603, 18.94716168, 22.8793152 ,
       24.20550074, 40.99019099, 20.72241496, 26.07043228,         nan,
       21.99766763, 42.6454166 , 31.43541219, 18.23201056, 37.13266399,
       28.74414786, 29.05051511, 26.64895768, 27.3655377 , 39.44103265,
        9.63416657,         nan,         nan, 38.89607993, 17.25358346,
       45.38436844, 28.696031  , 41.03373972, 49.0519146 , 42.79049868,
               nan, 23.35930229, 29.82751679, 16.42498538, 13.82508949,
       27.74785456, 31.77720409, 20.26720607, 30.6249583 , 44.93572171,
       30.05247132, 37.43658933, 41.23917353, 49.49279519, 32.1438831 ,
       41.3082567 , 48.31921933, 47.49843765, 11.34868319, 23.28765387,
       19.57955275,  8.91162567, 33.49583487, 38.11570759, 43.1657643 ,
       10.52496003, 44.43998341, 33.93165036,         nan, 45.97808016,
       33.1142572 , 20.11396357, 42.12982991, 21.33766455,  6.54026499,
       42.3794528 , 20.53364652, 39.82255354, 21.32410526, 43.7480609 ,
       14.87797363, 48.85462693, 40.08914487, 10.14070667, 30.4599479 ,
       49.34152905, 26.19794537, 13.19482125, 26.81502652,         nan,
       38.37591249, 36.44806339, 23.11475196, 14.81103984, 34.02743755,
       23.97667705, 10.9524295 , 45.52575356, 36.10498359, 35.74327354,
       42.01627442, 28.83477554, 41.67744928, 27.41408391,  8.022893  ,
       23.23616396, 27.38592023, 37.40911617,  9.79604286, 11.30083424,
       16.86577112, 16.9924277 , 37.94830603, 16.28287973, 33.48941285,
       27.24232326, 30.79824702, 42.71481334, 23.19716757, 39.69101197,
       23.99162268,         nan, 48.13822298, 13.29669143,  9.06516323,
       39.69436665,  8.07123674, 42.66855458, 24.67370284, 46.19811548,
       37.46897875, 32.46821002, 47.71880587, 22.84922179, 47.93391214,
       11.07505748, 26.76897239, 17.14600501, 29.29292505, 12.29062451,
       42.86883471, 43.08835322, 47.98563407, 11.96024634, 33.04996479,
       26.34067889, 20.49726794, 20.81930725, 23.57570978, 36.72164974,
       31.92287262, 25.68566807,  8.41700347,  8.49944048,  5.10527258,
       48.54647247,  5.23642184,  9.63921857, 19.15684506, 41.33436133,
       48.29444536, 40.55061015, 36.07521046, 28.45853003,  8.90173453,
       48.11768569, 39.12765863, 33.75272234, 39.15661305, 37.58464982,
       33.67542109, 49.12595601, 45.65137157, 34.09992136, 36.19288452,
        7.3218113 , 35.1462859 ,  6.9874447 , 31.47186906, 49.97090748,
       30.01129616, 26.29445531, 19.07846854, 10.42351605, 37.89606522,
       13.66695625, 10.18769096, 23.97931969, 40.79038271, 38.52790467,
        7.46971766, 25.48146583, 28.50955592, 34.00459928, 34.25753077,
       21.41137623,         nan, 26.64778477, 44.82492604, 28.86193097,
       24.84644728, 23.20184524, 30.75924917, 41.17896407, 29.22806707,
       34.77448288, 38.20350951, 28.40756494, 24.20676755, 44.449942  ,
       23.78777378, 25.78742828, 49.5653591 ,  5.01068856, 13.34628093,
       22.27837505, 46.96654592,  8.15133676,  5.42684451,  7.37077262,
        8.98445348,  6.69185479, 26.59015971, 31.13407433, 17.2259137 ,
       22.92293228,  9.12647008, 20.13667087, 28.51336362, 37.95223132,
        5.15058629, 26.02898449, 18.36512944,         nan, 37.19989919,
       31.50988405, 17.47695406, 45.96525959,  7.02953047,  9.92604194,
       22.62335632, 10.59969008, 48.03870639, 40.9095195 , 16.65421932,
       31.4849403 , 49.20487318, 44.78895402, 32.03593009, 45.66757852,
       49.51332094, 38.45087703,  7.92438843, 23.07111064, 42.70215809,
       15.37561381, 42.3789133 , 10.41524429,         nan, 22.28407752,
        6.65293718, 48.07716183, 42.17925631, 41.03463592, 33.34000653])

In [267]:

# TODO : Reflect the changes back into the whole matrix X
X[:, 2] = price
X

array([[6.00000000e+00, 4.10000000e+01, 2.06428647e+01, 1.00000000e+00,
        2.72843444e+00, 0.00000000e+00],
       [1.90000000e+01, 2.50000000e+01, 6.43121067e+00, 1.00000000e+00,
        2.22209726e+00, 1.00000000e+00],
       [2.80000000e+01, 3.40000000e+01, 2.96921889e+01, 3.00000000e+00,
        7.33352852e-02, 1.00000000e+00],
       ...,
       [1.50000000e+01, 4.00000000e+00, 4.21792563e+01, 1.00000000e+00,
        4.54695096e+00, 0.00000000e+00],
       [6.00000000e+00, 1.70000000e+01, 4.10346359e+01, 1.00000000e+00,
        3.90106532e+00, 1.00000000e+00],
       [2.80000000e+01, 2.70000000e+01, 3.33400065e+01, 1.00000000e+00,
        3.51460191e-02, 0.00000000e+00]])

In [268]:

print("NaN indices (price):", nan_idx[:10])
print("Sample price values with NaNs:", price[nan_idx[:5]])

NaN indices (price): [431 157 267  34 266  63 493  49 468 254]
Sample price values with NaNs: [nan nan nan nan nan]


## 3) Simple clean-up using masks

- Detect NaNs with `np.isnan`  
- Impute them with `0.0` using `np.where`
- Update the table `X`

In [269]:

# TODO :  Detect NaNs in price , Hint ## Google isnan method
is_nan_price = np.isnan(price)
print("NaN count in price:", int(is_nan_price.sum()))

NaN count in price: 15

In [270]:

# TODO : Replace NAN with 0.0 otherwise the price
price = np.where(is_nan_price, 0.0, price)

In [271]:
# Update X with the new price
X[:, 2] = price

In [272]:

# Quick check
print("After impute — NaN count in price:", int(np.isnan(price).sum()))

After impute — NaN count in price: 0


## 4) Basic summaries

- Number of paid rows (`np.where(...).size`)  

- Average **qty** for paid rows

In [273]:

## TODO : obtain the paid idx only using np.where
paid_idx = np.where(price) 

# TODO : Get the size the paid indecies, search for .size
num_paid = np.size(paid_idx)

In [274]:

avg_qty_paid = qty[paid_idx].mean() if num_paid>0 else 0.0

print("Paid rows:", num_paid, "of", N)
print("Average qty (paid rows):", round(avg_qty_paid, 2))

Paid rows: 485 of 500
Average qty (paid rows): 2.98


## 5) Slicing & masks

- Select rows where `day in [10, 14]`  
- Replace all `qty == 1` with `2` using `np.where`  
- Find indices where `qty == 5` **and** `paid == 1`

In [278]:

## TODO : Select rows where day in [10, 14]
mid_rows = np.where(np.isin(day, [10, 14]))[0]
print("Rows where day in [10,14]:", mid_rows.size)
print(np.round(X[mid_rows[:5]], 2))

Rows where day in [10,14]: 26
[[14.   49.   29.05  4.    2.94  1.  ]
 [10.   24.   21.02  2.    0.84  1.  ]
 [10.    7.   28.02  1.    4.07  0.  ]
 [10.   45.   12.06  3.    0.54  1.  ]
 [14.   29.   20.43  2.    4.12  0.  ]]

In [ ]:
# TODO Replace qty==1 with 2
qty = 
X[??] = qty #TODO Replace in x
print("Changed qty==1 -> 2. Sample qty values:", qty[:10])

SyntaxError: invalid syntax (1787542217.py, line 2)

In [ ]:
# TODO Positions where qty==5 AND paid==1
hit = ?? [0]
print("Indices with qty==5 and paid==1 (first 10):", hit[:10])


## 6) 2D array play — `reshape`, swap rows/cols, reverse, stack

- Take the first 12 rows × 3 columns (`day,item,price`)  
- `reshape` to 4×9  
- Swap the first two **columns** (use `np.copy`)  
- Swap the first two **rows**  
- Reverse rows with `np.flipud`  
- Vertically stack the result with itself (`np.vstack`)

In [ ]:
tiny = ??      # TODO copy the first 12 rows × 3 columns (day,item,price )
A = tiny.??        # TODO reshape 4×9

In [ ]:
print("A shape:", A.shape)
print("A (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# TODO Swap first two columns
A_copy = ??
A[:, 0] = ??
A[:, 1] =??
print("\nAfter swapping first two columns (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# TODO Swap first two rows
A2 = np.copy(A)
A[0, :], A[1, :] = ??
print("\nAfter swapping first two rows (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# TODO Reverse rows
A = ??
print("\nAfter reversing rows (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# Stack A with itself versically
A_stacked = ??
print("\nStacked shape:", A_stacked.shape)


## 7) Percentile threshold on `price`

- Use `np.percentile` to compute the 90th percentile of **price** among paid rows  
- Flag rows where `price >= p90`

In [ ]:
paid_price = price[paid==1] ## TODO : obtain price for paid ==1

In [ ]:
p90 = ?? #TODO search how to obtain percentile 90

In [ ]:
flag_hi = ?? [0] # TODO : Flag rows where price >= p90

In [ ]:
print(f"90th percentile of price (paid rows): {p90:.2f}")
print("First 10 high-price indices:", flag_hi[:10])


## 8) Linspace & simple binning for `price`

- Create evenly spaced **price checkpoints** with `np.linspace`

In [ ]:

# Price checkpoints
checkpoints = ??  # Create evenly spaced price checkpoints with linespace (GOOGLE)
print("Price checkpoints:", np.round(checkpoints, 2))


## 9) What You Practiced

- Random data: `np.random.seed`, `np.random.choice`, `np.random.uniform`, `np.arange`  
- Masking & replacement: `np.where`, `np.isnan`  
- 2D shaping: `reshape`, `np.copy`, row/column swaps, `np.flipud`, `np.vstack`  
- Simple stats: `np.percentile`, basic sums and means  
- Utilities: `np.linspace`